[server]
hostname = "localhost"
port = "5000"
key = "geDb76JMcsmxJGkTr28rceAQD4q10T8d"
threads = 8

[cert]
port = "4000"
domain = "tagify.gchq.icu"
email = "it.networking.logging@gmail.com"
path = "certs"
timeout = 5000
activate = false

[default_admin]
username = "admin"
nickname = "admin"
password = "admin"
role = "admin"

[default_user]
username = "user"
nickname = "user"
password = "user"
role = "user"

[postgres]
user = "example"
password = "example"
dbname = "example"
host = "localhost"
port = "5432"

[tagify_data]
path = "./tagify_data"
google_storage_enable = "false"
project_number = ""
